### ISSUE TITLE
Install Preset Command prompt always returns None

### ISSUE THREAD

**Issue by mikemartin** [studio1902/statamic-peak-commands#17]
### Bug description

When making a selection on the Install Preset prompt, the command returns "None".
<img width="653" alt="Screenshot 2023-08-14 at 1 11 12 pm" src="https://github.com/studio1902/statamic-peak-commands/assets/414211/c1088931-6b81-4001-9cfc-0fbf7c570832">

### How to reproduce

`php please peak:install-preset`
`Select preset and hit Enter`

### Environment

```yaml
Environment
Application Name: Coates Group
Laravel Version: 10.17.1
PHP Version: 8.1.17
Composer Version: 2.4.0
Environment: local
Debug Mode: ENABLED
URL: coatesgroup.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 10
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.17.0 PRO

Statamic Addons
aerni/social-links: 3.1.0
codedge/statamic-move-entries: dev-main
jonassiewertsen/statamic-livewire: 2.12.0
ncla/statamic-focal-point-fieldtype: 3.0.0
rias/statamic-color-swatches: 2.2.0
studio1902/statamic-peak-browser-appearance: 3.2
studio1902/statamic-peak-commands: 2.3.2
studio1902/statamic-peak-seo: 5.0
studio1902/statamic-peak-tools: 3.2
swiftmade/statamic-clear-assets: 2.0.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
