### ISSUE TITLE
Typo in Clients preset instructions

### ISSUE THREAD

**Issue by ashermiddleton** [studio1902/statamic-peak-commands#27]
### Bug description

There's a typo in the locale strings preset instructions for the Clients preset, the comment and newline has been forgotten before the string content, see [here](https://github.com/studio1902/statamic-peak-commands/blob/dcacb7be6effe62b9986150b187d69046f24e087/src/Commands/InstallPresetPresets.php#L150). Not sure if {{ name }} or {{ handle }} should be used here so haven't made a PR.

### How to reproduce

Run `php please peak:install:preset` and select `Clients`.

### Environment

```yaml
Laravel Version: 11.23.5
PHP Version: 8.3.10

Statamic
Addons: 4
Sites: 2
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.25.0 PRO

Statamic Addons
studio1902/statamic-peak-browser-appearance: 3.5.0
studio1902/statamic-peak-commands: 8.8.1
studio1902/statamic-peak-seo: 8.16.0
studio1902/statamic-peak-tools: 6.3.2
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
