### ISSUE TITLE
Business hours incorrectly shows closed status for opening times spanning midnight

### ISSUE THREAD

**Issue by porstendorfer** [studio1902/statamic-peak-commands#29]
### Bug description

The business hours component incorrectly determines the open/closed status when business hours span across midnight (e.g., 16:00 to 01:00 the next day). The component shows "Closed" when it should show "Open" during valid business hours such as 00:15.

### How to reproduce

1. Set up business hours for a day (e.g., Friday) that span across midnight:
- Opening time: 16:00
- Closing time: 01:00 (next day)
2. Visit the website during these time ranges:
- Between 16:00 and 23:59 (should show "Open")
- Between 00:00 and 01:00 (should show "Open")
3. Observe that the status incorrectly shows as "Closed" during these times

```yaml
title: 'Business hours'
data:
  dates:
    -
      id: KcwMv4Y3
      weekday: monday
      open: false
    -
      id: RwZ13bUE
      weekday: tuesday
      open: true
      start_time: '16:00'
      end_time: '00:00'
    -
      id: AlCrWZYJ
      weekday: wednesday
      open: true
      start_time: '16:00'
      end_time: '00:00'
    -
      id: OdYNnHKv
      weekday: thursday
      open: true
      start_time: '16:00'
      end_time: '00:00'
    -
      id: vbusJ5GT
      weekday: friday
      open: true
      start_time: '16:00'
      end_time: '01:00'
    -
      id: 3HjTxO3Y
      weekday: saturday
      open: true
      start_time: '16:00'
      end_time: '01:00'
    -
      id: YKXcMIJA
      weekday: sunday
      open: false
  phone_number: '06 12 34 56 78'
```

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: ///
Laravel Version: 11.41.3
PHP Version: 8.3.16
Composer Version: 2.8.4
Environment: local
Debug Mode: ENABLED
URL: hl.test
Maintenance Mode: OFF
Timezone: Europe/Berlin
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 5
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.46.0 PRO

Statamic Addons
statamic/ssg: 3.1.0
studio1902/statamic-peak-browser-appearance: 3.6.0
studio1902/statamic-peak-commands: 8.16.1
studio1902/statamic-peak-seo: 8.19.0
studio1902/statamic-peak-tools: 6.7.1
```

### Installation

Starter Kit using via CLI

### Antlers Parser

None
